#!/bin/bash

_pivpn() {
    local cur opts

    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    dashopts='-a -c -d -l -qr -r -h -u -up -bk -off -on'
    opts='add clients debug list qrcode remove help uninstall update backup (temp) off (temp) on'

    if [ ${#COMP_WORDS[@]} -eq 2 ]
    then
        [[ "${cur}" =~ ^-.*$ ]] && \
            COMPREPLY=( $(compgen -W "${dashopts}" -- "${cur}") ) || \
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
    fi
}

complete -F _pivpn pivpn
